### ISSUE TITLE
Manga entry with null links causes error.

### ISSUE THREAD

**Issue by rslink** [ejnshtein/mangadex-api#1]
Cannot convert undefined or null to object

When trying to get by id a manga where the links value is null.

Also happens when it has no chapters.

**Comment by ejnshtein** [comment]
Can you send me code example?

**Comment by rslink** [comment]
As an example: 
`cosnt manga = await Mangadex.getManga(16460, true).catch((error) => {
     console.error(error);
 })`

Will error with:
Cannot convert undefined or null to object
because `manga.manga.links` is  `null`

The manga with id 24648 will also error as it has no chapters.
