### ISSUE TITLE
How can i skip this Error, or get this? and my woker dont stop still runing

### ISSUE THREAD

**Issue by onepiecehung** [ejnshtein/mangadex-api#10]
![image](https://user-images.githubusercontent.com/24888125/79572102-92167480-80e6-11ea-932f-8d5213f31f0c.png)
If this package get id mangadex don't exist, the program will be stopped, how can program still running when have error

**Comment by ejnshtein** [comment]
Catch error.

like
`
try {  
 await Mangadex.getManga(227233)  
} catch (e) {  
console.log('error here: ', e)  
}
`

**Comment by onepiecehung** [comment]
> Catch error.
> 
> like
> `try { await Mangadex.getManga(227233) } catch (e) { console.log('error here: ', e) }`

![image](https://user-images.githubusercontent.com/24888125/79627093-a185d400-815f-11ea-94be-9cfc8c210fd0.png)
I did try it, but it's not working!!! program will be stopped!!! I can't get this error.

**Comment by ejnshtein** [comment]
hmmm, I found a mistake, working on it

**Comment by ejnshtein** [comment]
Update to v2.0.6, I fixed it

**Comment by onepiecehung** [comment]
> Update to v2.0.6, I fixed it

yeah,  The program did not stop hybrid on v2.0.6 thanks you,
But when you update this package to v2.0.7, I think you need to get the error to JSON, now we can get the error, we can get it in the new version, thanks
![image](https://user-images.githubusercontent.com/24888125/79692180-f45da980-828d-11ea-8853-d9688b09553b.png)

**Comment by ejnshtein** [comment]
If you want to catch error via `try {} catch (e) {}` you need to use async await.  
Otherwise, Promise.catch.

**Comment by ejnshtein** [comment]
I mean,  
`
try { const result = await Mangadex.getManga(227233);console.log(result) } catch (e) { console.log('error: ', e) }
`

Like this.

**Comment by onepiecehung** [comment]
> I mean,
> `try { const result = await Mangadex.getManga(227233);console.log(result) } catch (e) { console.log('error: ', e) }`
> 
> Like this.

Thanks, it's everything I want, this issue can be close!
