### ISSUE TITLE
Agent.callApi is returning a string and not an object

### ISSUE THREAD

**Issue by wc3betterthansc** [ejnshtein/mangadex-api#11]
The result of this github example: 

```
const Mangadex = require('mangadex-api')

Mangadex.getManga(22723).then(({ manga, chapter }) => {
  console.log(`Manga ${manga.title} has ${chapter.length} chapters.`)
})
```

is "Cannot read property 'cover_url' of undefined"

After debugging I noticed that the function Agent.callApi is returning a string, which is then passed to the normalizeManga function, which tries to destructure the string and fails so the manga variable will always be equal to undefined.

**Comment by ejnshtein** [comment]
Try v2.0.9

**Comment by wc3betterthansc** [comment]
> Try v2.0.9

It works with 2.0.9, thank you.
