### ISSUE TITLE
Incorrect types for search

### ISSUE THREAD

**Issue by JipFr** [ejnshtein/mangadex-api#14]
The  `search` method's first argument is typed as `searchQuery`, when it's actually just a string. 

Is the current behaviour incorrect, or is the type incorrect?

This time I made sure I was on the latest version :P

**Comment by ejnshtein** [comment]
Yeah, looks it should be `SearchQuery | string` type.

**Comment by JipFr** [comment]
Should I submit a PR or will you do it?

**Comment by ejnshtein** [comment]
Ok, should be fixed in V3.0.4

**Comment by JipFr** [comment]
Sweet, thanks!
