### ISSUE TITLE
Empty search results

### ISSUE THREAD

**Issue by JipFr** [ejnshtein/mangadex-api#17]
I've signed in but am getting an empty array of search results when it was working fine before. This stopped working after the update.

When I log `finalParams` on line 98 of `Mangadex.js`, I get
```json
{ "title": "Tower of God", "tag_mode_inc_all": "all", "tag_mode_exc": "any" }
```
When I look at `result` on that same line, it's a lot of HTML. It does appear to have my search results in the HTML:
```html
                    <div class="row m-0 col-auto p-0">
                        <div class="col-md-5 col-lg-7 p-0">
                            <div class="row m-0">
                                <div class="p-1 col d-flex align-items-center text-truncate flex-nowrap">
                                    <div><span class='rounded flag flag-kr' title='Korean'></span></div>                                    <a title="Tower of God"
                                       href="/title/1/tower-of-god"
                                       class="ml-1 manga_title text-truncate">Tower of God</a>
```
I just managed to narrow it down to the `parseSearch` method in `Scraper.js`.

As it turns out, changing the type of "display mode" on the MD search page also changes the DOM, thus ruining the `pageSearch` method. Anything that isn't "detailed" has mangadex-api show 0 results.

![Image of nav](https://user-images.githubusercontent.com/17685409/94789923-dc11bf00-03d5-11eb-9207-a53b55cf5d11.png)

I'm not sure what the best way to fix this would be. Any ideas?

**Comment by ejnshtein** [comment]
If I recall correctly, search view is setting by variable in cookie, you can try passing it in options for search method for now.
I'll fix it in next release.

**Comment by ejnshtein** [comment]
No, turns out this option is set on mangadex BE.
Now with v3.0.6, you can call `client.setMangaView(0)` to set manga list view to be detailed.

**Comment by JipFr** [comment]
That's interesting. How about better (error) handling for this specific case? It took me a while to figure out and I imagine I might not be the only one, since this is quite an interesting bug to figure out if you're not sure what you're looking for.

**Comment by ejnshtein** [comment]
Like, warn in console or smth?
But what if that's on purpose? 🤔

Also, I left a [note](https://github.com/ejnshtein/mangadex-api#search) in search method description

**Comment by JipFr** [comment]
A warning in the console would be nice, I'd say that's better than leaving people wondering why there are no search results. Alternatively, perhaps a check for each type could be added so it works regardless of what style list you choose.

I will say I think it's interesting MD would actually change the HTML. Personally, I would've just hidden some elements and re-styled it with CSS.

**Comment by JipFr** [comment]
Closing because there's a new API.
