### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by LeonardoToniolo** [ejnshtein/mangadex-api#19]
hello,

im receiving the following error

```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Node.parseTopMangaFollows (Scraper.js:222)
    at traversing.js:306
    at _baseReduce.js:18
    at _createBaseEach.js:24
    at baseReduce (_baseReduce.js:15)
    at Object.reduce (reduce.js:48)
    at initialize.webpackHotUpdate../node_modules/cheerio/lib/api/traversing.js.exports.map (traversing.js:305)
    at Function.parseHome (Scraper.js:271)
    at Function.getHome (Mangadex.js:192)
```

my projects uses ReactJS+ElectronJS,
at my home.tsx im using

```
Mangadex.getHome().then((home) => {
      setTopMangas(home.top_manga.rating)
      setLatestUpdates(home.latest_updates.all)
      setTopChapters(home.top_chapters.six_hours)
})
```

can anyone assist me in this question?

**Comment by ejnshtein** [comment]
This method is based on HTML scraping.
If you look into[ where the error was thrown](https://github.com/ejnshtein/mangadex-api/blob/4ad342495a05f64210135628b6bdcd888c0103a1/src/Scraper.js#L222) you'll see that mangadex has changed their layout in HTML and this method is dead for now.

I can suggest you call this method yourself with client.agent.call('/') and parse it or wait for the fix.

**Comment by LeonardoToniolo** [comment]
thanks!!
