### ISSUE TITLE
NSFW Search Result

### ISSUE THREAD

**Issue by raf555** [ejnshtein/mangadex-api#26]
Some of the search result from **Mangadex.search** returns an NSFW result, I think for some people this may be a huge concern.

I have two ideas for this issue, 
1. Add another parameter to **Mangadex.search** to enable/disable the NSFW result.
2. Give an indicator to the manga from search result that indicating that manga is NSFW or not.

Either one is fine at least the NSFW result can be disabled.
Thank you!

**Comment by ejnshtein** [comment]
Can you give example H manga?

**Comment by raf555** [comment]
i am terribly sorry i can't provide the example because i forgot what keywords that i used to search and accidentally found the H-manga, i think you can try to find it yourself since probably mangadex has a lot of them already

**Comment by ejnshtein** [comment]
As for now, you can log in to an account that you use for API and disable H manga from viewing.
I'm still working on it, so the update is coming soon.

**Comment by ejnshtein** [comment]
Okay, [v4.6.0](https://github.com/ejnshtein/mangadex-api/releases/tag/v4.6.0) is released with support to control NSFW results in search.
Also, I added a test for it!

**Comment by raf555** [comment]
Thank you so much for the work! Gonna try it later.

**Comment by ejnshtein** [comment]
Added NSFW example to docs in [v4.6.1](https://github.com/ejnshtein/mangadex-api/releases/tag/v4.6.1).

**Comment by raf555** [comment]
I already tried it and works just fine.
I will close this issue and might open it again in the future if I found similar issue, once again, thank you!

**Comment by ejnshtein** [comment]
👍
