### ISSUE TITLE
Manga search result is not showing proper views count for more than million views

### ISSUE THREAD

**Issue by raf555** [ejnshtein/mangadex-api#28]
I just realized this when using the search API. The result does not show the proper views count when the views count is more than a million. Here are the examples:

One Punch Man, should be 11,845,929 views, instead showing 11,845
Kaguya Love is war, should be 4,463,086, instead showing 4,463
And other manga too

Hope you can fix it, thank you.

![image](https://user-images.githubusercontent.com/8206338/107844903-0a82ba80-6e0a-11eb-9b2d-aafaaf9ba996.png)
![image](https://user-images.githubusercontent.com/8206338/107844936-4fa6ec80-6e0a-11eb-8ee1-b591b1ebd243.png)
![image](https://user-images.githubusercontent.com/8206338/107844895-0060bc00-6e0a-11eb-8753-d356b4b0c1ec.png)
![image](https://user-images.githubusercontent.com/8206338/107844939-546ba080-6e0a-11eb-9c32-cd7ce2e4b538.png)

**Comment by ejnshtein** [comment]
Thanks for the report!
Truly weird one 🤔 
Will be fixed in the next version!

**Comment by ejnshtein** [comment]
Fixed in [v4.6.3](https://github.com/ejnshtein/mangadex-api/releases/tag/v4.6.3)

**Comment by raf555** [comment]
Thank you for the fix!
