### ISSUE TITLE
Issue Creating Account with Api

### ISSUE THREAD

**Issue by KingMaxime** [ejnshtein/mangadex-api#38]
`I` have been try to create account using this package but it does not seems to work 

It keep throwing the error createAccount is not a function

Here my code 
```const { mangaDex } = require('mangadex-api')
const client = new mangaDex ()

const createUser = async(user, pass, email) =>{
try{
await client.account.createAccount(user, pass, email)
} catch(e){
console.log(e)
}
}

createUser (user, pass, email)
```

**Comment by ejnshtein** [comment]
Yes, createAccount is a static method ATM.

**Comment by KingMaxime** [comment]
Sorry am still a beginner so I don't really understand what that mean 

So how can I create account then

**Comment by KingMaxime** [comment]
So am I going to import Account Resolver then 

Like

```const { AccountResolver }  = require('mangadex-api')

const client = new AccountResolver ()

async function create(user, pass, email){
await client.createAccount(user, pass, email)
}

create()
```

**Comment by ejnshtein** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

**Comment by KingMaxime** [comment]
@ejnshtein Okay that means I can only Import Account Resolver and use right? 

Like

AccountResolver.createAccount()

Similar as AuthResolver

**Comment by KingMaxime** [comment]
I suggest you provide more docs or examples on creating account with this module because it really not good for beginners to try to use 

But anyway thanks I think my problem solved already

**Comment by ejnshtein** [comment]
Yeah, I'll be adding more docs when I finish building the library.

**Comment by KingMaxime** [comment]
@ejnshtein Cool✌️

**Comment by KingMaxime** [comment]
mangaDex API always return an [Error](https://api.mangadex.org/docs.html#section/Captchas) and I receive a siteKey to solve the recaptcha now my question is what can u do with the siteKey ??
